<p style="text-align:center">
    <a href="https://www.ict.mahidol.ac.th/en/" target="_blank">
    <img src="https://www3.ict.mahidol.ac.th/ICTSurveysV2/Content/image/MUICT2.png" width="400" alt="Faculty of ICT">
    </a>
</p>

# Lab03: Numerical Computation for Data Science

This lab assignment will test your understanding of NumPy, SciPy, and Pandas for data manipulation and analysis. It consists of two tasks, covering 1D and 2D NumPy arrays, SciPy statistical functions, and real-world data analysis. Complete the tasks below and submit your Jupyter Notebook.

__Intructions:__
1. Append your ID at the end of this jupyter file name. For example, ```ITCS227_Lab03_Assignment_6788123.ipynb```
2. Complete each task in the lab.
3. Once finished, raise your hand to call a TA.
4. The TA will check your work and give you an appropriate score.
5. Submit the source code to MyCourse as record-keeping.

## Task 01: NumPy 1D Arrays

Let's first import numpy.

In [83]:
import numpy as np

### Array Creation

a) Create a 1D NumPy array named 'arr1' containing the integers from 10 to 20 (inclusive).

In [84]:
# Your code here
import numpy as np
# arr = np.array([10,11,12,13,14,15,16,17,18,19,20])
arr1 = np.arange(10,21)
print("arr1:",arr1)

arr1: [10 11 12 13 14 15 16 17 18 19 20]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
arr1 = np.arange(10,21)
print("arr1:", arr1)
```
Output:
```
arr1: [10 11 12 13 14 15 16 17 18 19 20]
```
</details>

b) Create a 1D NumPy array named 'arr2' containing 10 evenly spaced numbers between 0 and 1 (inclusive).

In [85]:
# Your code here
arr2 = np.linspace(0,1,10)
print("arr2:",arr2)

arr2: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
arr2 = np.linspace(0,1,10)
print("\narr2:", arr2)
```
Output:
```
arr2: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
```
</details>

c) Create a 1D NumPy array named 'arr3' containing 5 random integers between 1 and 10 (inclusive).

In [86]:
# Your code here
arr3 = np.random.randint(1,11,5)
print("arr3: ",arr3)

arr3:  [9 1 6 8 7]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
arr3 = np.random.randint(1,11,5)
print("\narr3:", arr3)
```
Output:
```
arr3: [ 2  2  4 10  3]
```
</details>

### Array Operations
a) Calculate the sum of all elements in 'arr1'. Store the result in 'sum_arr1'.

In [87]:
# Your code here
sum_arr1 = np.sum(arr1)
print("sum_arr1:", sum_arr1)

sum_arr1: 165


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
sum_arr1 = np.sum(arr1)
print("\nSum of arr1:", sum_arr1)
```
Output:
```
Sum of arr1: 165
```
</details>

b) Calculate the mean of all elements in 'arr2'. Store the result in 'mean_arr2'.

In [88]:
# Your code here
mean_arr2 = np.mean(arr2)
print("mean_arr2",mean_arr2)

mean_arr2 0.5


c) Multiply each element in 'arr3' by 2. Store the result in 'arr3_multiplied'.

In [89]:
# Your code here
arr3_multiplied = np.multiply(arr3,2)
print("arr3_mul:", arr3_multiplied)

arr3_mul: [18  2 12 16 14]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
arr3_multiplied = arr3 * 2
print("arr3 multiplied by 2:",arr3_multiplied)
```
Output:
```
arr3 multiplied by 2: [ 4  4  8 20  6]
```
</details>

d) Calculate the dot product of 'arr1' and 'arr3'. Store the result in 'dot_product'. Note: arr1 and arr3 have different sizes, so you will need to take the first 5 elements of arr1 to compute the dot product

In [90]:
# Your code here

dot_product = np.dot(arr1[:5],arr3)
print("dot_product:",dot_product)

dot_product: 375


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
dot_product = np.dot(arr1[:5],arr3)
print("Dot product of arr1[:5] and arr3:",dot_product))
```
Output:
```
Dot product of arr1[:5] and arr3: 262
```
</details>

### Array Indexing and Slicing
a) Extract the first 3 elements of 'arr1' and store them in 'first_three'.

In [91]:
# Your code here
first_three = arr1[:3]
print(first_three)


[10 11 12]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
first_three = arr1[:3]
print("\nFirst three elements of arr1:",first_three)
```
Output:
```
First three elements of arr1: [10 11 12]
```
</details>

b) Extract the last 4 elements of 'arr2' and store them in 'last_four'.

In [92]:
# Your code here
last_four = arr2[-4:]
print("lastFour:",last_four)

lastFour: [0.66666667 0.77777778 0.88888889 1.        ]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
last_four = arr2[-4:]
print("Last four elements of arr2:",last_four)
```
Output:
```
Last four elements of arr2: [0.66666667 0.77777778 0.88888889 1.        ]
```
</details>

c) Extract every other element of 'arr1' starting from the second element (index 1) and store them in 'every_other'.

In [93]:
# Your code here
every_other = arr1[1:]
print("every_other:",every_other)

every_other: [11 12 13 14 15 16 17 18 19 20]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
every_other = arr1[1::2]
print("Every other element of arr1 starting from the second element:",every_other)
```
Output:
```
Every other element of arr1 starting from the second element: [11 13 15 17 19]
```
</details>

## Task 02: NumPy 2D Arrays

### Array Creation

a) Create a 2D NumPy array named 'matrix1' with shape (3, 4) containing integers from 1 to 12.

In [94]:
#import numpy as np #Uncomment if needed
import numpy as np
matrix1 = np.arange(1,13).reshape(3,4)
print(matrix1),

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(None,)

In [95]:
# Your code here

<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
matrix1 = np.arange(1,13).reshape(3,4)
print("\nmatrix1:\n",matrix1)
```
Output:
```
matrix1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```
</details>

b) Create a 2D NumPy array named 'matrix2' with shape (4, 2) containing random floating-point numbers between 0 and 1.

In [96]:
# Your code here
matrix2 = np.random.rand(4,2)
print("Matrix2 =",matrix2)

Matrix2 = [[0.41914163 0.63381511]
 [0.38866258 0.5013927 ]
 [0.16527971 0.85221098]
 [0.42199884 0.96147701]]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
matrix2 = np.random.rand(4,2)
print("\nmatrix2:\n",matrix2)
```
Output:
```
matrix2:
 [[0.93888543 0.95916952]
 [0.14125115 0.4530356 ]
 [0.38127538 0.97827993]
 [0.30541794 0.00375518]]
```
**Note**: The numbers may differ due to randomness.
    
</details>

c) Create a 2D NumPy array named 'identity_matrix' that is a 4x4 identity matrix.

In [97]:
# Your code here
identity_matrix = np.eye(4)
print("identity_matrix:\n",identity_matrix)

identity_matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
identity_matrix = np.eye(4)
print("\nidentity_matrix:\n",identity_matrix)
```
Output:
```
identity_matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```
</details>

### Array Operations
a) Calculate the element-wise sum of 'matrix1' and a new matrix with the same shape containing all ones. Store the result in 'matrix1_plus_ones'.

In [98]:
# Your code here
matrix1_plus_ones = matrix1 + np.ones(matrix1.shape)
print("matrix1sum:\n",matrix1_plus_ones)

matrix1sum:
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
matrix1_plus_ones = matrix1 + np.ones(matrix1.shape)
print("\nmatrix1 + ones:\n",matrix1_plus_ones)
```
Output:
```
matrix1 + ones:
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
```
</details>

b) Perform matrix multiplication (dot product) of 'matrix1' and 'matrix2'. Store the result in 'matrix_mult'.

In [99]:
# Your code here
matrix_mult = np.dot(matrix1,matrix2)
print(matrix_mult)

[[ 3.38030127  8.03914147]
 [ 8.96063231 19.83472465]
 [14.54096335 31.63030783]]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
matrix_mult = np.dot(matrix1,matrix2)
print("\nmatrix1 * matrix2:\n",matrix_mult)
```
Output:
```
matrix1 * matrix2:
 [[ 3.58688565  4.81510121]
 [10.65420527 14.3920621 ]
 [17.72152489 23.969023  ]]
```
</details>

c) Calculate the transpose of 'matrix1'. Store the result in 'matrix1_transposed'.

In [122]:
# Your code here
matrix1_transposed = np.transpose(matrix1)
print(matrix1_transposed)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
matrix1_transposed = matrix1.T
print("\nTranspose of matrix1:\n",matrix1_transposed)
```
Output:
```
Transpose of matrix1:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
```
</details>

d) Calculate the sum of each column in 'matrix1'. Store the result in 'column_sums'.

In [130]:
# Your code here
column_sums = np.sum(matrix1, axis = 0)
print(matrix1)


print("col_sum",column_sums)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
col_sum [15 18 21 24]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
column_sums = np.sum(matrix1,axis=0)
print("\nSum of each column in matrix1:",column_sums)
```
Output:
```
Sum of each column in matrix1: [15 18 21 24]
```
</details>

e) Calculate the mean of each row in 'matrix1'. Store the result in 'row_means'.

In [131]:
# Your code here
row_means = np.mean(matrix1,axis = 1)
print("row_mean",row_means)

row_mean [ 2.5  6.5 10.5]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
row_means = np.mean(matrix1,axis=1)
print("Mean of each row in matrix1:",row_means)
```
Output:
```
Mean of each row in matrix1: [ 2.5  6.5 10.5]
```
</details>

### Array Indexing and Slicing
a) Extract the element at row 1, column 2 of 'matrix1'. Store the result in 'element'.

In [132]:
# Your code here
element = matrix1[1,2]
print(element)

7


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
element = matrix1[1,2]
print("\nElement at row 1, column 2 of matrix1:",element)
```
Output:
```
Element at row 1, column 2 of matrix1: 7
```
</details>

b) Extract the first two rows of 'matrix1' and store them in 'first_two_rows'.

In [153]:
# Your code here
first_two_rows = matrix1[:2]
print(first_two_rows)

[[1 2 3 4]
 [5 6 7 8]]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
first_two_rows = matrix1[:2,:]
print("First two rows of matrix1:\n",first_two_rows)
```
Output:
```
First two rows of matrix1:
 [[1 2 3 4]
 [5 6 7 8]]
```
</details>

c) Extract the last column of 'matrix1' and store it in 'last_column'.

In [155]:
# Your code here
last_column = matrix1[:,-1]
print(last_column)

[ 4  8 12]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
last_column = matrix1[:,-1]
print("Last column of matrix1:",last_column)
```
Output:
```
Last column of matrix1: [ 4  8 12]
```
</details>

d) Extract a submatrix from 'matrix1' consisting of rows 0 and 1, and columns 1 and 2. Store it in 'submatrix'.

In [158]:
# Your code here
submatrix = matrix1[:2,1:3]
print(submatrix)

[[2 3]
 [6 7]]


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
submatrix = matrix1[:2,1:3]
print("Submatrix of matrix1:\n",submatrix)
```
Output:
```
Submatrix of matrix1:
 [[2 3]
 [6 7]]
```
</details>

## Task 03: Analyzing Student Performance
This task uses the Student Performance in Exams dataset to explore relationships between various factors and student scores. You will practice using Pandas, Numpy, and Scipy to analyze real-world data, as well as get a glimpse on simple visualization techniques.

In [107]:
# Install necessary libraries (if you haven't already):
# !pip install pandas numpy scipy matplotlib seaborn

import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt # for simple plots
import seaborn as sns # for better plots

First of all, read 'files/StudentsPerformance.csv' into the dataframe `df`.

In [160]:
# Your code here
df = pd.read_csv("files/StudentsPerformance.csv")
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72         

<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
try:
    df = pd.read_csv('files/StudentsPerformance.csv')
except FileNotFoundError:
    print("Please upload the StudentsPerformance.csv file or place it in the same directory as the notebook")
    raise #stop execution
```
</details>

Then, explore the dataset a little bit. Show the first 5 rows, and explore the dataframe's basic information using `.info()`.

In [164]:
# Your code here
print(df.head())
print(df.info())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtyp

<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
print("First 5 rows of the dataset:")
print(df.head())
print("Dataset Info:")
df.info()
```
Output:
```
First 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  
Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
```
</details>

### Basic Descriptive Statistics (Pandas/NumPy)
a) What is the average math, reading, and writing score?

In [168]:
# Your code here
print("Math",round(df['math score'].mean(),2))
print("reading",round(df['reading score'].mean(),2))
print("writing",round(df['writing score'].mean(),2))

Math 66.09
Math 69.17
Math 68.05


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
avg_math = df['math score'].mean()
avg_reading = df['reading score'].mean()
avg_writing = df['writing score'].mean()
print(f"\nAverage Math Score: {avg_math:.2f}")
print(f"Average Reading Score: {avg_reading:.2f}")
print(f"Average Writing Score: {avg_writing:.2f}")
```
Output:
```
Average Math Score: 66.09
Average Reading Score: 69.17
Average Writing Score: 68.05
```
</details>

b) What is the standard deviation of each score?

In [173]:
# Your code here
print("Math std",round(np.std(df['math score']),2))
print("reading std",round(np.std(df['reading score']),2))
print("writing std",round(np.std(df['writing score']),2))


Math std 15.16
reading std 14.59
writing std 15.19


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
std_math = df['math score'].std()
std_reading = df['reading score'].std()
std_writing = df['writing score'].std()
print(f"\nStandard Deviation Math Score: {std_math:.2f}")
print(f"Standard Deviation Reading Score: {std_reading:.2f}")
print(f"Standard Deviation Writing Score: {std_writing:.2f}")
```
Output:
```
Standard Deviation Math Score: 15.16
Standard Deviation Reading Score: 14.60
Standard Deviation Writing Score: 15.20
```
</details>

c) What is the range (max - min) of math scores?

In [178]:
# Your code here
print((df['math score'].max()) - (df['math score'].min()))


100


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
math_range = df['math score'].max() - df['math score'].min()
print(f"\nRange of Math Scores: {math_range}"))
```
Output:
```
Range of Math Scores: 100
```
</details>

### Grouped Statistics (Pandas)
a) What is the average math score for each gender?

In [180]:
# Your code here
print((df.groupby('gender')['math score'].mean()))


gender
female    63.633205
male      68.728216
Name: math score, dtype: float64


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
avg_math_by_gender = df.groupby('gender')['math score'].mean()
print("\nAverage Math Score by Gender:\n", avg_math_by_gender)
```
Output:
```
Average Math Score by Gender:
 gender
female    63.633205
male      68.728216
Name: math score, dtype: float64
```
</details>

b) What is the average reading score for each parental level of education?

In [182]:
# Your code here
print((df.groupby('parental level of education')['reading score'].mean()))


parental level of education
associate's degree    70.927928
bachelor's degree     73.000000
high school           64.704082
master's degree       75.372881
some college          69.460177
some high school      66.938547
Name: reading score, dtype: float64


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
avg_reading_by_parental_education = df.groupby('parental level of education')['reading score'].mean()
print("\nAverage Reading Score by Parental Education:\n", avg_reading_by_parental_education)
```
Output:
```
Average Reading Score by Parental Education:
 parental level of education
associate's degree    70.927928
bachelor's degree     73.000000
high school           64.704082
master's degree       75.372881
some college          69.460177
some high school      66.938547
Name: reading score, dtype: float64
```
</details>

c) Which race/ethnicity group has the highest average writing score?

In [194]:
avg_by_race = df.groupby('race/ethnicity')['writing score'].mean()
highest_writing_race = avg_by_race.idxmax()
print(f"\nRace/Ethnicity with Highest Average Writing Score: {highest_writing_race}")


Race/Ethnicity with Highest Average Writing Score: group E


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
avg_writing_by_race = df.groupby('race/ethnicity')['writing score'].mean()
highest_writing_race = avg_writing_by_race.idxmax()
print(f"\nRace/Ethnicity with Highest Average Writing Score: {highest_writing_race}")
```
Output:
```
Race/Ethnicity with Highest Average Writing Score: group E
```
</details>

### Correlation Analysis (NumPy/SciPy)

a) Is there a correlation between math score and reading score?

In [199]:
# Your code here
correlation_math_reading = np.corrcoef(df['math score'], df['reading score'])[0, 1]
print(f"\nCorrelation = {correlation_math_reading:.2f}")


Correlation = 0.82


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
correlation_math_reading = np.corrcoef(df['math score'], df['reading score'])[0, 1]
print(f"\nCorrelation between Math and Reading Scores: {correlation_math_reading:.2f}")
```
Output:
```
Correlation between Math and Reading Scores: 0.82
```
</details>

b) Perform a statistical test (Pearson correlation) to determine if the correlation between writing and reading score is statistically significant.

In [204]:
# Your code here
correlation_writing_reading = stats.pearsonr(df['writing score'], df['reading score'])
print(f"Correlation = {correlation_writing_reading}")


Correlation = PearsonRResult(statistic=np.float64(0.9545980771462479), pvalue=np.float64(0.0))


<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
correlation_writing_reading = stats.pearsonr(df['writing score'], df['reading score'])
print(f"Correlation test between Writing and Reading scores: {correlation_writing_reading}")
```
Output:
```
Correlation test between Writing and Reading scores: PearsonRResult(statistic=0.9545980771462478, pvalue=0.0)
```
</details>

## Optional: Introduction to Basic Data Visualization (Matplotlib/Seaborn)

a) Create a box plot to visualize the distribution of math scores by lunch type.

In [118]:
# Your code here

<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
plt.figure(figsize=(8, 6))
sns.boxplot(x='lunch', y='math score', data=df)
plt.title('Math Scores by Lunch Type')
plt.show()
```
</details>

b) Create a violin plot to visualize the distribution of writing scores by race/ethnicity.

In [119]:
# Your code here

<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

```python
plt.figure(figsize=(10, 6))
sns.violinplot(x='race/ethnicity', y='writing score', data=df)
plt.title('Writing Scores by Race/Ethnicity')
plt.show()
```
</details>

## Optional: Advanced Questions about the Data

a) Does test preparation course seem to have an impact on student performance? How can you analyze this?

In [120]:
# Your answer here

<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

A possible answer:
```
We can compare the average scores of students who took the test preparation course with those who didn't using group statistics or statistical tests like t-tests.
```
</details>

b) Are there any interactions between parental level of education and race/ethnicity in terms of student performance? How could you investigate this?

In [121]:
# Your answer here

<details><summary><span style="color:red">Help</span> (Use this only as a last resort!!)</summary>

A possible answer:
```
We could use groupby with multiple columns (e.g., df.groupby(['parental level of education', 'race/ethnicity']) and calculate average scores to see if there are any combined effects.
```
</details>

<p style="text-align:center;">That's it! Congratulations! <br> 
    Now, call an LA to check your solution. Then, upload your code on MyCourses.</p>